"""Course content, written once per topic and translated into every course language.

Shape
    vocab:     (english, emoji, spanish, french, (japanese, kana, romaji))
    sentences: (english, spanish, french, (japanese tokens, kana tokens, romaji))

Japanese has no spaces between words, so its sentences are written as
space-separated tokens: the tokens become word-bank tiles and hint targets,
and the displayed sentence is the tokens joined without spaces. Learners may
answer Japanese in kanji/kana, hiragana only, or romaji.
"""

LANGUAGES = {
    # code: (course title, flag, speech locale, words separated by spaces?)
    "es": ("Spanish", "🇪🇸", "es-ES", True),
    "fr": ("French", "🇫🇷", "fr-FR", True),
    "ja": ("Japanese", "🇯🇵", "ja-JP", False),
    "hi": ("Hindi", "🇮🇳", "hi-IN", True),
}

# Languages written in their own script: they start with that script, letters are heard on
# their own, and a romanized spelling is accepted wherever the script is.
SCRIPTS = {"ja", "hi"}

# Function words, so hints work beyond the skill's vocabulary.
GLOSSARY = {
    "es": {"yo": "I", "tú": "you", "él": "he", "ella": "she", "es": "is", "un": "a", "una": "a", "mi": "my",
           "el": "the", "la": "the", "con": "with", "en": "in / on", "soy": "I am", "eres": "you are",
           "está": "is", "estoy": "I am", "me": "me / myself", "bebe": "drinks", "come": "eats", "como": "I eat",
           "tengo": "I have", "quiere": "wants", "voy": "I go", "al": "to the", "a": "to"},
    "fr": {"je": "I", "j'ai": "I have", "tu": "you", "il": "he", "elle": "she", "est": "is", "un": "a",
           "une": "a", "le": "the", "la": "the", "l'": "the", "mon": "my", "ma": "my", "du": "some",
           "de": "of / some", "avec": "with", "et": "and", "suis": "am", "es": "are", "boit": "drinks",
           "mange": "eats", "au": "to the", "à": "to", "c'est": "it is", "nous": "we", "dans": "in"},
    "ja": {"は": "(topic marker)", "を": "(object marker)", "が": "(subject marker)", "に": "to / in",
           "で": "at", "の": "'s / of", "と": "and", "か": "(question)", "です": "is / am", "私": "I",
           "あなた": "you", "彼": "he", "彼女": "she", "私たち": "we", "この": "this", "ます": "(polite)",
           "食べます": "eat(s)", "飲みます": "drink(s)", "行きます": "go", "男": "man", "元気": "well",
           "お元気": "well (polite)", "好き": "like", "大きい": "big", "います": "there is / have"},
    "hi": {"है": "is (hai)", "हैं": "are (hain)", "हूँ": "am (hoon)", "हो": "are (ho)", "मैं": "I (main)",
           "तुम": "you (tum)", "आप": "you, polite (aap)", "वह": "he / she (vah)", "हम": "we (hum)",
           "मेरा": "my (mera)", "मेरी": "my (meri)", "मेरे": "my (mere)", "एक": "a / one (ek)", "का": "of (ka)",
           "के": "of (ke)", "की": "of (ki)", "में": "in (mein)", "पर": "on (par)", "से": "from / with (se)",
           "साथ": "with (saath)", "को": "to (ko)", "और": "and (aur)", "कहाँ": "where (kahaan)", "पास": "near / have (paas)",
           "पीता": "drinks (peeta)", "पीती": "drinks (peeti)", "खाता": "eats (khaata)", "खाती": "eats (khaati)",
           "खाते": "eat (khaate)", "मुझे": "to me (mujhe)", "चाहिए": "need / want (chahiye)", "इस": "this (is)",
           "नाम": "name (naam)", "कैसे": "how (kaise)", "ठीक": "fine (theek)", "बड़ा": "big (bada)"},
}

COURSE = [
    ("Order in a café", "Greet people and order food and drinks", "#58cc02", [
        ("Basics", "🥚",
         [("the boy", "👦", "el niño", "le garçon", ("男の子", "おとこのこ", "otokonoko")),
          ("the girl", "👧", "la niña", "la fille", ("女の子", "おんなのこ", "onnanoko")),
          ("the man", "👨", "el hombre", "l'homme", ("男の人", "おとこのひと", "otokonohito")),
          ("the woman", "👩", "la mujer", "la femme", ("女の人", "おんなのひと", "onnanohito")),
          ("the water", "💧", "el agua", "l'eau", ("水", "みず", "mizu")),
          ("the apple", "🍎", "la manzana", "la pomme", ("りんご", "りんご", "ringo"))],
         [("The boy drinks water.", "El niño bebe agua.", "Le garçon boit de l'eau.",
           ("男の子 は 水 を 飲みます", "おとこのこ は みず を のみます", "otokonoko wa mizu o nomimasu")),
          ("The woman eats an apple.", "La mujer come una manzana.", "La femme mange une pomme.",
           ("女の人 は りんご を 食べます", "おんなのひと は りんご を たべます", "onnanohito wa ringo o tabemasu")),
          ("I am a man.", "Yo soy un hombre.", "Je suis un homme.",
           ("私 は 男 です", "わたし は おとこ です", "watashi wa otoko desu")),
          ("You are a girl.", "Tú eres una niña.", "Tu es une fille.",
           ("あなた は 女の子 です", "あなた は おんなのこ です", "anata wa onnanoko desu")),
          ("The girl eats an apple.", "La niña come una manzana.", "La fille mange une pomme.",
           ("女の子 は りんご を 食べます", "おんなのこ は りんご を たべます", "onnanoko wa ringo o tabemasu"))]),
        ("Greetings", "👋",
         [("hello", "👋", "hola", "bonjour", ("こんにちは", "こんにちは", "konnichiwa")),
          ("goodbye", "🚪", "adiós", "au revoir", ("さようなら", "さようなら", "sayounara")),
          ("thank you", "🙏", "gracias", "merci", ("ありがとう", "ありがとう", "arigatou")),
          ("please", "🥺", "por favor", "s'il vous plaît", ("お願いします", "おねがいします", "onegaishimasu")),
          ("excuse me", "🙋", "perdón", "pardon", ("すみません", "すみません", "sumimasen")),
          ("good night", "🌙", "buenas noches", "bonne nuit", ("おやすみなさい", "おやすみなさい", "oyasuminasai"))],
         [("Hello, my name is Ana.", "Hola, me llamo Ana.", "Bonjour, je m'appelle Ana.",
           ("こんにちは 私 は アナ です", "こんにちは わたし は アナ です", "konnichiwa watashi wa ana desu")),
          ("Thank you, goodbye.", "Gracias, adiós.", "Merci, au revoir.",
           ("ありがとう さようなら", "ありがとう さようなら", "arigatou sayounara")),
          ("How are you?", "¿Cómo estás?", "Comment ça va ?",
           ("お元気 です か", "おげんき です か", "ogenki desu ka")),
          ("I am well, thank you.", "Estoy bien, gracias.", "Je vais bien, merci.",
           ("元気 です ありがとう", "げんき です ありがとう", "genki desu arigatou")),
          ("Good night, Ana.", "Buenas noches, Ana.", "Bonne nuit, Ana.",
           ("おやすみなさい アナ", "おやすみなさい アナ", "oyasuminasai ana"))]),
        ("Café", "☕",
         [("the coffee", "☕", "el café", "le café", ("コーヒー", "コーヒー", "koohii")),
          ("the bread", "🍞", "el pan", "le pain", ("パン", "パン", "pan")),
          ("the milk", "🥛", "la leche", "le lait", ("牛乳", "ぎゅうにゅう", "gyuunyuu")),
          ("the cheese", "🧀", "el queso", "le fromage", ("チーズ", "チーズ", "chiizu")),
          ("the tea", "🍵", "el té", "le thé", ("お茶", "おちゃ", "ocha")),
          ("the soup", "🍲", "la sopa", "la soupe", ("スープ", "スープ", "suupu"))],
         [("A coffee, please.", "Un café, por favor.", "Un café, s'il vous plaît.",
           ("コーヒー を お願いします", "コーヒー を おねがいします", "koohii o onegaishimasu")),
          ("I eat bread with cheese.", "Yo como pan con queso.", "Je mange du pain avec du fromage.",
           ("私 は チーズ と パン を 食べます", "わたし は チーズ と パン を たべます", "watashi wa chiizu to pan o tabemasu")),
          ("She drinks milk.", "Ella bebe leche.", "Elle boit du lait.",
           ("彼女 は 牛乳 を 飲みます", "かのじょ は ぎゅうにゅう を のみます", "kanojo wa gyuunyuu o nomimasu")),
          ("The soup is hot.", "La sopa está caliente.", "La soupe est chaude.",
           ("スープ は 熱い です", "スープ は あつい です", "suupu wa atsui desu")),
          ("He wants tea.", "Él quiere té.", "Il veut du thé.",
           ("彼 は お茶 が 欲しい です", "かれ は おちゃ が ほしい です", "kare wa ocha ga hoshii desu"))]),
    ]),
    ("Talk about your family", "Describe people, pets and colors", "#ce82ff", [
        ("Family", "👪",
         [("the mother", "👩", "la madre", "la mère", ("お母さん", "おかあさん", "okaasan")),
          ("the father", "👨", "el padre", "le père", ("お父さん", "おとうさん", "otousan")),
          ("the sister", "👧", "la hermana", "la sœur", ("姉", "あね", "ane")),
          ("the brother", "👦", "el hermano", "le frère", ("兄", "あに", "ani")),
          ("the grandfather", "👴", "el abuelo", "le grand-père", ("おじいさん", "おじいさん", "ojiisan")),
          ("the grandmother", "👵", "la abuela", "la grand-mère", ("おばあさん", "おばあさん", "obaasan"))],
         [("My mother is tall.", "Mi madre es alta.", "Ma mère est grande.",
           ("母 は 背 が 高い です", "はは は せ が たかい です", "haha wa se ga takai desu")),
          ("I have a brother.", "Tengo un hermano.", "J'ai un frère.",
           ("私 は 兄 が います", "わたし は あに が います", "watashi wa ani ga imasu")),
          ("My grandmother cooks well.", "Mi abuela cocina bien.", "Ma grand-mère cuisine bien.",
           ("祖母 は 料理 が 上手 です", "そぼ は りょうり が じょうず です", "sobo wa ryouri ga jouzu desu")),
          ("He is my father.", "Él es mi padre.", "C'est mon père.",
           ("彼 は 私 の 父 です", "かれ は わたし の ちち です", "kare wa watashi no chichi desu")),
          ("My sister reads a book.", "Mi hermana lee un libro.", "Ma sœur lit un livre.",
           ("姉 は 本 を 読みます", "あね は ほん を よみます", "ane wa hon o yomimasu"))]),
        ("Animals", "🐶",
         [("the dog", "🐶", "el perro", "le chien", ("犬", "いぬ", "inu")),
          ("the cat", "🐱", "el gato", "le chat", ("猫", "ねこ", "neko")),
          ("the bird", "🐦", "el pájaro", "l'oiseau", ("鳥", "とり", "tori")),
          ("the horse", "🐴", "el caballo", "le cheval", ("馬", "うま", "uma")),
          ("the fish", "🐟", "el pez", "le poisson", ("魚", "さかな", "sakana")),
          ("the cow", "🐮", "la vaca", "la vache", ("牛", "うし", "ushi"))],
         [("The dog eats.", "El perro come.", "Le chien mange.",
           ("犬 は 食べます", "いぬ は たべます", "inu wa tabemasu")),
          ("I have a black cat.", "Tengo un gato negro.", "J'ai un chat noir.",
           ("私 は 黒い 猫 を 飼っています", "わたし は くろい ねこ を かっています", "watashi wa kuroi neko o katteimasu")),
          ("The bird sings.", "El pájaro canta.", "L'oiseau chante.",
           ("鳥 が 歌います", "とり が うたいます", "tori ga utaimasu")),
          ("The cow drinks water.", "La vaca bebe agua.", "La vache boit de l'eau.",
           ("牛 は 水 を 飲みます", "うし は みず を のみます", "ushi wa mizu o nomimasu")),
          ("The horse is big.", "El caballo es grande.", "Le cheval est grand.",
           ("馬 は 大きい です", "うま は おおきい です", "uma wa ookii desu"))]),
        ("Colors", "🎨",
         [("red", "🔴", "rojo", "rouge", ("赤", "あか", "aka")),
          ("blue", "🔵", "azul", "bleu", ("青", "あお", "ao")),
          ("green", "🟢", "verde", "vert", ("緑", "みどり", "midori")),
          ("yellow", "🟡", "amarillo", "jaune", ("黄色", "きいろ", "kiiro")),
          ("black", "⚫", "negro", "noir", ("黒", "くろ", "kuro")),
          ("white", "⚪", "blanco", "blanc", ("白", "しろ", "shiro"))],
         [("The car is red.", "El coche es rojo.", "La voiture est rouge.",
           ("車 は 赤い です", "くるま は あかい です", "kuruma wa akai desu")),
          ("I like blue.", "Me gusta el azul.", "J'aime le bleu.",
           ("私 は 青 が 好き です", "わたし は あお が すき です", "watashi wa ao ga suki desu")),
          ("The apple is green.", "La manzana es verde.", "La pomme est verte.",
           ("りんご は 緑 です", "りんご は みどり です", "ringo wa midori desu")),
          ("The sun is yellow.", "El sol es amarillo.", "Le soleil est jaune.",
           ("太陽 は 黄色い です", "たいよう は きいろい です", "taiyou wa kiiroi desu")),
          ("My cat is white.", "Mi gato es blanco.", "Mon chat est blanc.",
           ("私 の 猫 は 白い です", "わたし の ねこ は しろい です", "watashi no neko wa shiroi desu"))]),
    ]),
    ("Get around town", "Travel, places and telling time", "#1cb0f6", [
        ("Travel", "✈️",
         [("the train", "🚆", "el tren", "le train", ("電車", "でんしゃ", "densha")),
          ("the plane", "✈️", "el avión", "l'avion", ("飛行機", "ひこうき", "hikouki")),
          ("the hotel", "🏨", "el hotel", "l'hôtel", ("ホテル", "ホテル", "hoteru")),
          ("the passport", "🛂", "el pasaporte", "le passeport", ("パスポート", "パスポート", "pasupooto")),
          ("the beach", "🏖️", "la playa", "la plage", ("ビーチ", "ビーチ", "biichi")),
          ("the ticket", "🎫", "el billete", "le billet", ("切符", "きっぷ", "kippu"))],
         [("The train arrives late.", "El tren llega tarde.", "Le train arrive en retard.",
           ("電車 が 遅れて います", "でんしゃ が おくれて います", "densha ga okurete imasu")),
          ("I need my passport.", "Necesito mi pasaporte.", "J'ai besoin de mon passeport.",
           ("パスポート が 必要 です", "パスポート が ひつよう です", "pasupooto ga hitsuyou desu")),
          ("The hotel is near.", "El hotel está cerca.", "L'hôtel est proche.",
           ("ホテル は 近い です", "ホテル は ちかい です", "hoteru wa chikai desu")),
          ("We go to the beach.", "Vamos a la playa.", "Nous allons à la plage.",
           ("私たち は ビーチ に 行きます", "わたしたち は ビーチ に いきます", "watashitachi wa biichi ni ikimasu")),
          ("I buy a ticket.", "Compro un billete.", "J'achète un billet.",
           ("私 は 切符 を 買います", "わたし は きっぷ を かいます", "watashi wa kippu o kaimasu"))]),
        ("Places", "🏛️",
         [("the city", "🏙️", "la ciudad", "la ville", ("町", "まち", "machi")),
          ("the museum", "🏛️", "el museo", "le musée", ("博物館", "はくぶつかん", "hakubutsukan")),
          ("the park", "🌳", "el parque", "le parc", ("公園", "こうえん", "kouen")),
          ("the street", "🛣️", "la calle", "la rue", ("道", "みち", "michi")),
          ("the restaurant", "🍽️", "el restaurante", "le restaurant", ("レストラン", "レストラン", "resutoran")),
          ("the school", "🏫", "la escuela", "l'école", ("学校", "がっこう", "gakkou"))],
         [("Where is the museum?", "¿Dónde está el museo?", "Où est le musée ?",
           ("博物館 は どこ です か", "はくぶつかん は どこ です か", "hakubutsukan wa doko desu ka")),
          ("The park is pretty.", "El parque es bonito.", "Le parc est joli.",
           ("公園 は きれい です", "こうえん は きれい です", "kouen wa kirei desu")),
          ("I live in the city.", "Vivo en la ciudad.", "J'habite en ville.",
           ("私 は 町 に 住んでいます", "わたし は まち に すんでいます", "watashi wa machi ni sundeimasu")),
          ("The school is on this street.", "La escuela está en esta calle.", "L'école est dans cette rue.",
           ("学校 は この 道 に あります", "がっこう は この みち に あります", "gakkou wa kono michi ni arimasu")),
          ("We eat at a restaurant.", "Comemos en un restaurante.", "Nous mangeons au restaurant.",
           ("私たち は レストラン で 食べます", "わたしたち は レストラン で たべます", "watashitachi wa resutoran de tabemasu"))]),
        ("Time", "⏰",
         [("today", "📅", "hoy", "aujourd'hui", ("今日", "きょう", "kyou")),
          ("tomorrow", "⏭️", "mañana", "demain", ("明日", "あした", "ashita")),
          ("the hour", "⏰", "la hora", "l'heure", ("時間", "じかん", "jikan")),
          ("the week", "🗓️", "la semana", "la semaine", ("週", "しゅう", "shuu")),
          ("the day", "☀️", "el día", "le jour", ("日", "ひ", "hi")),
          ("the night", "🌙", "la noche", "la nuit", ("夜", "よる", "yoru"))],
         [("Today is Monday.", "Hoy es lunes.", "Aujourd'hui, c'est lundi.",
           ("今日 は 月曜日 です", "きょう は げつようび です", "kyou wa getsuyoubi desu")),
          ("Tomorrow I go to the park.", "Mañana voy al parque.", "Demain, je vais au parc.",
           ("明日 公園 に 行きます", "あした こうえん に いきます", "ashita kouen ni ikimasu")),
          ("What time is it?", "¿Qué hora es?", "Quelle heure est-il ?",
           ("今 何時 です か", "いま なんじ です か", "ima nanji desu ka")),
          ("The night is cold.", "La noche es fría.", "La nuit est froide.",
           ("夜 は 寒い です", "よる は さむい です", "yoru wa samui desu")),
          ("I work all week.", "Trabajo toda la semana.", "Je travaille toute la semaine.",
           ("一週間 ずっと 働きます", "いっしゅうかん ずっと はたらきます", "isshuukan zutto hatarakimasu"))]),
    ]),
]

# Extra accepted English translations (grading already ignores case/accents/punctuation).
ALTERNATES = {
    "I am a man.": ["I'm a man"], "You are a girl.": ["You're a girl"],
    "I am well, thank you.": ["I'm well, thank you", "I am fine, thank you", "I'm fine, thanks", "I am well, thanks"],
    "Thank you, goodbye.": ["Thanks, goodbye", "Thank you, bye"], "The hotel is near.": ["The hotel is close"],
    "We go to the beach.": ["Let's go to the beach", "We are going to the beach"],
    "Tomorrow I go to the park.": ["Tomorrow I am going to the park", "I go to the park tomorrow"],
    "Hello, my name is Ana.": ["Hello, I am Ana", "Hi, my name is Ana"], "The park is pretty.": ["The park is beautiful"],
    "What time is it?": ["What's the time"], "I like blue.": ["I like the color blue"],
    "He wants tea.": ["He wants a tea", "He wants some tea"], "She drinks milk.": ["She is drinking milk"],
    "I eat bread with cheese.": ["I eat cheese and bread", "I eat bread and cheese"],
    "We eat at a restaurant.": ["We eat in a restaurant"], "The school is on this street.": ["The school is in this street"],
    "I work all week.": ["I work the whole week"], "My grandmother cooks well.": ["My grandmother is good at cooking"],
}

# The first skill of every course: how the language is written and sounds, before any words.
# One group per lesson: (letter, sound, example word to hear). Japanese kana are heard on their own.
ALPHABET = {
    "ja": ("Hiragana", "あ", [
        [("あ", "a", "あ"), ("い", "i", "い"), ("う", "u", "う"), ("え", "e", "え"), ("お", "o", "お")],
        [("か", "ka", "か"), ("き", "ki", "き"), ("く", "ku", "く"), ("け", "ke", "け"), ("こ", "ko", "こ")],
        [("さ", "sa", "さ"), ("し", "shi", "し"), ("す", "su", "す"), ("せ", "se", "せ"), ("そ", "so", "そ")],
    ]),
    "es": ("Letters & sounds", "🔤", [
        [("a", "ah", "agua"), ("e", "eh", "leche"), ("i", "ee", "niño"), ("o", "oh", "hola"), ("u", "oo", "uno")],
        [("ñ", "ny, as in canyon", "niño"), ("ll", "y, as in yes", "llamo"), ("j", "h, as in hello", "jugo"),
         ("rr", "rolled r", "perro"), ("h", "silent", "hola")],
    ]),
    "hi": ("Devanagari", "अ", [
        [("अ", "a", "अ"), ("आ", "aa", "आ"), ("इ", "i", "इ"), ("ई", "ee", "ई"), ("उ", "u", "उ")],
        [("क", "ka", "क"), ("ख", "kha", "ख"), ("ग", "ga", "ग"), ("घ", "gha", "घ"), ("च", "cha", "च")],
        [("त", "ta", "त"), ("द", "da", "द"), ("न", "na", "न"), ("प", "pa", "प"), ("म", "ma", "म")],
    ]),
    "fr": ("Letters & sounds", "🔤", [
        [("é", "ay, as in say", "café"), ("è", "eh, as in bed", "mère"), ("ç", "s, as in sun", "français"),
         ("ê", "eh, as in get", "fête"), ("à", "ah, as in father", "voilà")],
        [("ou", "oo, as in food", "rouge"), ("oi", "wa, as in water", "moi"), ("an", "nasal ahn", "blanc"),
         ("on", "nasal ohn", "bonjour"), ("u", "ee with rounded lips", "rue")],
    ]),
}


# Hindi, keyed by the English above: (Devanagari, romanized). Kept apart from the tuples so the
# other languages' content stays as written.
HINDI = {
    "the boy": ("लड़का", "ladka"), "the girl": ("लड़की", "ladki"), "the man": ("आदमी", "aadmi"),
    "the woman": ("औरत", "aurat"), "the water": ("पानी", "paani"), "the apple": ("सेब", "seb"),
    "The boy drinks water.": ("लड़का पानी पीता है।", "ladka paani peeta hai"),
    "The woman eats an apple.": ("औरत सेब खाती है।", "aurat seb khaati hai"),
    "I am a man.": ("मैं आदमी हूँ।", "main aadmi hoon"),
    "You are a girl.": ("तुम लड़की हो।", "tum ladki ho"),
    "The girl eats an apple.": ("लड़की सेब खाती है।", "ladki seb khaati hai"),

    "hello": ("नमस्ते", "namaste"), "goodbye": ("अलविदा", "alvida"), "thank you": ("धन्यवाद", "dhanyavaad"),
    "please": ("कृपया", "kripya"), "excuse me": ("माफ़ कीजिए", "maaf kijiye"), "good night": ("शुभ रात्रि", "shubh raatri"),
    "Hello, my name is Ana.": ("नमस्ते, मेरा नाम आना है।", "namaste mera naam aana hai"),
    "Thank you, goodbye.": ("धन्यवाद, अलविदा।", "dhanyavaad alvida"),
    "How are you?": ("आप कैसे हैं?", "aap kaise hain"),
    "I am well, thank you.": ("मैं ठीक हूँ, धन्यवाद।", "main theek hoon dhanyavaad"),
    "Good night, Ana.": ("शुभ रात्रि, आना।", "shubh raatri aana"),

    "the coffee": ("कॉफ़ी", "coffee"), "the bread": ("रोटी", "roti"), "the milk": ("दूध", "doodh"),
    "the cheese": ("पनीर", "paneer"), "the tea": ("चाय", "chai"), "the soup": ("सूप", "soop"),
    "A coffee, please.": ("एक कॉफ़ी, कृपया।", "ek coffee kripya"),
    "I eat bread with cheese.": ("मैं पनीर के साथ रोटी खाता हूँ।", "main paneer ke saath roti khaata hoon"),
    "She drinks milk.": ("वह दूध पीती है।", "vah doodh peeti hai"),
    "The soup is hot.": ("सूप गरम है।", "soop garam hai"),
    "He wants tea.": ("उसे चाय चाहिए।", "use chai chahiye"),

    "the mother": ("माँ", "maa"), "the father": ("पिता", "pita"), "the sister": ("बहन", "bahan"),
    "the brother": ("भाई", "bhai"), "the grandfather": ("दादा", "dada"), "the grandmother": ("दादी", "dadi"),
    "My mother is tall.": ("मेरी माँ लंबी है।", "meri maa lambi hai"),
    "I have a brother.": ("मेरा एक भाई है।", "mera ek bhai hai"),
    "My grandmother cooks well.": ("मेरी दादी अच्छा खाना बनाती है।", "meri dadi achchha khaana banaati hai"),
    "He is my father.": ("वह मेरे पिता हैं।", "vah mere pita hain"),
    "My sister reads a book.": ("मेरी बहन किताब पढ़ती है।", "meri bahan kitaab padhti hai"),

    "the dog": ("कुत्ता", "kutta"), "the cat": ("बिल्ली", "billi"), "the bird": ("चिड़िया", "chidiya"),
    "the horse": ("घोड़ा", "ghoda"), "the fish": ("मछली", "machhli"), "the cow": ("गाय", "gaay"),
    "The dog eats.": ("कुत्ता खाता है।", "kutta khaata hai"),
    "I have a black cat.": ("मेरे पास एक काली बिल्ली है।", "mere paas ek kaali billi hai"),
    "The bird sings.": ("चिड़िया गाती है।", "chidiya gaati hai"),
    "The cow drinks water.": ("गाय पानी पीती है।", "gaay paani peeti hai"),
    "The horse is big.": ("घोड़ा बड़ा है।", "ghoda bada hai"),

    "red": ("लाल", "laal"), "blue": ("नीला", "neela"), "green": ("हरा", "hara"),
    "yellow": ("पीला", "peela"), "black": ("काला", "kaala"), "white": ("सफ़ेद", "safed"),
    "The car is red.": ("गाड़ी लाल है।", "gaadi laal hai"),
    "I like blue.": ("मुझे नीला रंग पसंद है।", "mujhe neela rang pasand hai"),
    "The apple is green.": ("सेब हरा है।", "seb hara hai"),
    "The sun is yellow.": ("सूरज पीला है।", "sooraj peela hai"),
    "My cat is white.": ("मेरी बिल्ली सफ़ेद है।", "meri billi safed hai"),

    "the train": ("ट्रेन", "train"), "the plane": ("हवाई जहाज़", "hawai jahaz"), "the hotel": ("होटल", "hotel"),
    "the passport": ("पासपोर्ट", "passport"), "the beach": ("समुद्र तट", "samudra tat"), "the ticket": ("टिकट", "ticket"),
    "The train arrives late.": ("ट्रेन देर से आती है।", "train der se aati hai"),
    "I need my passport.": ("मुझे अपना पासपोर्ट चाहिए।", "mujhe apna passport chahiye"),
    "The hotel is near.": ("होटल पास है।", "hotel paas hai"),
    "We go to the beach.": ("हम समुद्र तट जाते हैं।", "hum samudra tat jaate hain"),
    "I buy a ticket.": ("मैं टिकट खरीदता हूँ।", "main ticket kharidta hoon"),

    "the city": ("शहर", "shahar"), "the museum": ("संग्रहालय", "sangrahalay"), "the park": ("पार्क", "park"),
    "the street": ("सड़क", "sadak"), "the restaurant": ("रेस्टोरेंट", "restaurant"), "the school": ("स्कूल", "school"),
    "Where is the museum?": ("संग्रहालय कहाँ है?", "sangrahalay kahaan hai"),
    "The park is pretty.": ("पार्क सुंदर है।", "park sundar hai"),
    "I live in the city.": ("मैं शहर में रहता हूँ।", "main shahar mein rehta hoon"),
    "The school is on this street.": ("स्कूल इस सड़क पर है।", "school is sadak par hai"),
    "We eat at a restaurant.": ("हम रेस्टोरेंट में खाते हैं।", "hum restaurant mein khaate hain"),

    "today": ("आज", "aaj"), "tomorrow": ("कल", "kal"), "the hour": ("घंटा", "ghanta"),
    "the week": ("हफ़्ता", "hafta"), "the day": ("दिन", "din"), "the night": ("रात", "raat"),
    "Today is Monday.": ("आज सोमवार है।", "aaj somvaar hai"),
    "Tomorrow I go to the park.": ("कल मैं पार्क जाऊँगा।", "kal main park jaaunga"),
    "What time is it?": ("कितने बजे हैं?", "kitne baje hain"),
    "The night is cold.": ("रात ठंडी है।", "raat thandi hai"),
    "I work all week.": ("मैं पूरे हफ़्ते काम करता हूँ।", "main poore hafte kaam karta hoon"),
}
